import Gallery from "@/components/gallery/Gallery";
import Overview from "@/components/overview/Overview";
import TopProducts from "@/components/top-products/TopProducts";

import Head from "next/head";
const products = [
  {
    id: 0,
    title: "PURE SACCO Post Laser Gel Cream",
    price: 22.9,
    imgUrl: "/images/products/Mock up_page-0001.jpg",
    tags: ["جديد"],
  },
  {
    id: 1,
    title: "Hair Care product",
    price: 22.9,
    imgUrl: "/images/products/Mock up_page-0002.jpg",
    tags: ["جديد"],
  },
  {
    id: 2,
    title: "Hair Care product",
    price: 22.9,
    imgUrl: "/images/products/Mock up_page-0003.jpg",
    tags: ["جديد"],
  },
  {
    id: 3,
    title: "Hair Care product",
    price: 22.9,
    imgUrl: "/images/gallery/1.jpg",
    tags: ["جديد"],
  },
  {
    id: 2,
    title: "Hair Care product",
    price: 22.9,
    imgUrl: "/images/products/Mock up_page-0003.jpg",
    tags: ["جديد"],
  },
  {
    id: 3,
    title: "Hair Care product",
    price: 22.9,
    imgUrl: "/images/gallery/1.jpg",
    tags: ["جديد"],
  },
  {
    id: 2,
    title: "Hair Care product",
    price: 22.9,
    imgUrl: "/images/products/Mock up_page-0003.jpg",
    tags: ["جديد"],
  },
  {
    id: 3,
    title: "Hair Care product",
    price: 22.9,
    imgUrl: "/images/gallery/1.jpg",
    tags: ["جديد"],
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Pure Derma Egypt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/logo.png" />
      </Head>
      <Gallery />
      <Overview />
      <TopProducts products={products} />
    </>
  );
}
